bankproject/bank/urls.py
from django.urls import path
from . import views
app_name='bank'

urlpatterns = [
    path('',views.home,name='home'),
    path('login/',views.login,name='login'),
    path('register/',views.register,name='register'),
    path('form/',views.forms,name='forms'),
    path('logout/',views.logout,name='logout'),
    path('dist-json/',views.get_json_district,name='dist-json'),
    path('form/branch-json/<str:district>/',views.get_branches,name='branch-json'),
    path('success',views.success,name='success')
]

bankproject/bankproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bank.urls')),

]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

bankproject/bank/models.py
from django.db import models

# Create your models here.
class pdet(models.Model):
    name=models.CharField(max_length=250)
    age=models.IntegerField()
    dob=models.DateField()
    address=models.TextField(default="not given")
    mob=models.IntegerField()
    mail=models.EmailField()

class District(models.Model):
    name= models.CharField(max_length=250,blank=True,null=True)
    def __str__(self):
        return str(self.name)

class Branch(models.Model):
    name=models.CharField(max_length=250,blank=True,null=True)
    district=models.ForeignKey(District, on_delete=models.CASCADE, null=True)
    def __str__(self):
        return f"{self.district}-{self.name}"

bankproject/bank/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from .models import pdet,District,Branch
from django.views.generic import CreateView

from django.http import JsonResponse



# Create your views here.
def home(request):
    return render(request,'home.html')

def forms(request):
    if request.method == 'POST':
        name=request.POST['name']
        dob=request.POST['dob']
        age=request.POST['age']
        mob=request.POST['mob']
        mail=request.POST['mail']
        address=request.POST['address']
        person=pdet(name=name,dob=dob,age=age,mob=mob,mail=mail,address=address)
        person.save()
        messages.info(request,"information added successfully")
        return redirect('bank:success')


    district = District.objects.all()
    return render(request,'forms.html',{'district':district})

def get_json_district(request):
    dist_val=list(District.objects.values())
    return JsonResponse({'data':dist_val})

def get_branches(request, *args, **kwargs):
    selected_dist = kwargs.get('district')
    branch_val = list(Branch.objects.filter(district__id=selected_dist).values())
    return JsonResponse({'data':branch_val})

def success(request):
    details = pdet.objects.all()
    return render(request,'success.html',{'details':details})


def login(request):
    if request.method == 'POST':
        username=request.POST['username']
        password=request.POST['password']
        u=auth.authenticate(username=username,password=password)

        if u is not None:
            auth.login(request,u)
            return redirect('bank:forms')
        else:
            messages.info(request,"Invalid credentials")
            return redirect('bank:login')
    return render(request,'login.html')

def register(request):
    if request.method== 'POST':
        uname=request.POST['uname']
        password=request.POST['pass']
        cpass=request.POST['cpass']

        if password == cpass:
            if User.objects.filter(username=uname):
                print("username")
                # messages.info(request,"Username already exist")
                return redirect('bank:register')
            else:
                user=User.objects.create_user(username=uname,password=password)
                user.save()
                print("user")
                # messages.info(request,"user successfully created")
        else:
            print("pass")
            # messages.info(request,"passwords are not  matching")
            return redirect('bank:register')
        return redirect('bank:login')

    return render(request,'reg.html')

def logout(request):
    auth.logout(request)
    return redirect('/')

bankproject/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Welcome to MyBank</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Raleway:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/main.css' %}" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/a076d05399.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/solid.min.css" integrity="sha512-uj2QCZdpo8PSbRGL/g5mXek6HM/APd7k/B5Hx/rkVFPNOxAQMXD+t+bG4Zv8OAdUpydZTU3UHmyjjiHv2Ww0PA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<!--  new modal-->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css">
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
  <script>
    $(function() {
      $('[data-toggle="modal"]').on('click', function(e) {
        e.preventDefault();
        $(this).bsModal();
      });
    });
  </script>

  <style>
        .table1{
            border:2px;
            border-color:teal;

        }
        .form_input{
            width:350px;

        }
        .bg{

            background-size:contain;
            background-repeat:no-repeat;

        }
        .about{
            padding:50px;
            background:rgba(80,255,155,0.8);
            height:550px;

        }

        .text{

            padding-left:12%;
            font-size:25px;
            color:darkslategrey;
        }
        .form1{
            margin-top:30px;
            background:rgba(105,105,105,0.5);
            width:450px;
            height:550px;
            margin-left:37%;
            border-radius:25px;

        }
        .form2{
            margin-top:30px;
            background:rgba(105,140,200,0.8);
            width:450px;
            height:550px;
            margin-left:40%;
        }
        .h{
            color:white;
            padding:5px;
        }
        .input{
            width:300px;
            height:30px;
            padding-top:10px;
            margin-top:22px;
            padding-left:25px;
            background:rgba(230,230,250,0.9);
            border:none;
            border-radius:15px;

        }
        .input1{
            width:300px;
            height:30px;
            margin-top:50px;
            padding-top:10px;
            padding-left:25px;
            background:rgba(230,230,250,0.9);
            border:none;
            border-radius:15px;


        }
        .ft{
            color:rgba(227,247,269);
            display:inline-block;
            padding-left:12px;
            padding-top:12px;
            font-size:21px;
        }

    </style>

  <!-- =======================================================
  * Template Name: Nova - v1.3.0
  * Template URL: https://bootstrapmade.com/nova-bootstrap-business-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body class="page-index">

  <!-- ======= Header ======= -->
  <header id="header" class="header d-flex align-items-center fixed-top">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

      <a href="index.html" class="logo d-flex align-items-center">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="assets/img/logo.png" alt=""> -->
        <h1 class="d-flex align-items-center">MyBank</h1>
      </a>

      <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
      <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a href="{% url 'bank:home' %}" class="active">Home</a></li>
          {% if user.is_authenticated %}
            <li class="ft"><p>hello, {{ user.username }}</p></li>
            <li><a href="{% url 'bank:logout' %}">Logout</a></li>
          {% else %}
            <li><a href="{% url 'bank:login' %}">Login</a></li>
            <li><a href="{% url 'bank:register' %}">Register</a></li>
          {% endif %}
          <li class="dropdown"><a href="#"><span>Branches</span> <i class="bi bi-chevron-down dropdown-indicator"></i></a>
            <ul>
              <li><a href="https://en.wikipedia.org/wiki/Alappuzha">Alappuzha</a></li>
<!--              <li class="dropdown"><a href="#"><span>Deep Dropdown</span> <i class="bi bi-chevron-down dropdown-indicator"></i></a>-->
<!--                <ul>-->
<!--                  <li><a href="#">Deep Dropdown 1</a></li>-->
<!--                  <li><a href="#">Deep Dropdown 2</a></li>-->
<!--                  <li><a href="#">Deep Dropdown 3</a></li>-->
<!--                  <li><a href="#">Deep Dropdown 4</a></li>-->
<!--                  <li><a href="#">Deep Dropdown 5</a></li>-->
<!--                </ul>-->
<!--              </li>-->
              <li><a href="https://en.wikipedia.org/wiki/Ernakulam">Ernakulam</a></li>
              <li><a href="https://en.wikipedia.org/wiki/Kannur">Kannur</a></li>
              <li><a href="https://en.wikipedia.org/wiki/Kollam">Kollam</a></li>
              <li><a href="https://en.wikipedia.org/wiki/Kozhikode">Kozhikode</a></li>
              <li><a href="https://en.wikipedia.org/wiki/Palakkad">Palakkad</a></li>
              <li><a href="https://en.wikipedia.org/wiki/Pathanamthitta">Pathanamthitta</a></li>
              <li><a href="https://en.wikipedia.org/wiki/Trivandrum">Trivandrum</a></li>
            </ul>
          </li>
        </ul>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->
  {% block content %}
  {% endblock %}

<!--  &lt;!&ndash; ======= Hero Section ======= &ndash;&gt;-->

  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">

    <div class="footer-content">
      <div class="container">
        <div class="row gy-4">
          <div class="col-lg-5 col-md-12 footer-info">
            <a href="index.html" class="logo d-flex align-items-center">
              <span>MyBank</span>
            </a>
            <p>More than just banking, all about companionship.</p>
            <div class="social-links d-flex  mt-3">
              <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
              <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
              <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
              <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
            </div>
          </div>

<!--          <div class="col-lg-2 col-6 footer-links">-->
<!--            <h4>Useful Links</h4>-->
<!--            <ul>-->
<!--              <li><i class="bi bi-dash"></i> <a href="#">Home</a></li>-->
<!--              <li><i class="bi bi-dash"></i> <a href="#">About us</a></li>-->
<!--              <li><i class="bi bi-dash"></i> <a href="#">Services</a></li>-->
<!--              <li><i class="bi bi-dash"></i> <a href="#">Terms of service</a></li>-->
<!--              <li><i class="bi bi-dash"></i> <a href="#">Privacy policy</a></li>-->
<!--            </ul>-->
<!--          </div>-->


          <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
            <h4>Contact Us</h4>
            <p>
              A108 Adam Street <br>
              cochin,  535022<br>
              Kerala <br><br>

            </p>

          </div>
          <div class="col-lg-2 col-6 footer-links">
            <p>
              <strong>Phone:</strong>+91 589 55488 55<br>
              <strong>Email:</strong>info@mybank.com<br>
            </p>
          </div>


        </div>
      </div>
    </div>

    <div class="footer-legal">
      <div class="container">
        <div class="copyright">
          &copy; Copyright <strong><span>MyBank</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nova-bootstrap-business-template/ -->
          Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
      </div>
    </div>
  </footer><!-- End Footer -->
  <!-- End Footer -->

  <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>
  <script src="{% static 'assets/js/modal.js' %}"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>

</html>

bankproject/templates/login.html
{% extends 'index.html' %}
{% block content %}
<section id="hero" class="hero d-flex align-items-center">
    <div class="container">
      <div class="row">
        <div class="col-xl-4">
          <h2 data-aos="fade-up">Focus On What Matters</h2>
          <blockquote data-aos="fade-up" data-aos-delay="100">
            <p> More than just banking, all about companionship.</p>
          </blockquote>


        </div>
        <div class="col-md-6">
          <div align="center" class="form1" >
            <form action="{% url 'bank:login' %}" method="post">
                {% csrf_token %}
                <div class="display-2 " align="center">
                    <h2 class="h"><b>LOGIN</b></h2>
                </div>
                <div class="form-group" >
                  <i class="fa fa-user" style="font-size:25px"></i> <input class=" input1" type="text" name="username" >
                </div>
                <div class="form-group">
                  <i class="fa fa-lock" style="font-size:25px"></i> <input class="input" type="password"  name="password" >
                </div>
                <div class="form-check">
                  <a type="label" href="" style="color:wheat"><b>forgot password</b></a>
                  <a type="label" href="{% url 'bank:register' %}" style="color:wheat"><b>New user click here</b> </a>
                </div><br><br>

                <button type="submit" class="btn-get-started">Login</button>

<!--            <a href="https://www.youtube.com/watch?v=LXb3EKWsInQ" class="glightbox btn-watch-video d-flex align-items-center"><i class="bi bi-play-circle"></i><span>Watch Video</span></a>-->


            </form>
        </div>
        </div>
      </div>
    </div>
  </section><!-- End Hero Section -->

{% endblock %}

bankproject/templates/reg.html
{% extends 'index.html' %}
{% block content %}
<section id="hero" class="hero d-flex align-items-center">
    <div class="container">
      <div class="row">
        <div class="col-xl-4">
          <h2 data-aos="fade-up">Join Our Family</h2>
          <blockquote data-aos="fade-up" data-aos-delay="100">
            <p> simply complete the registration process and feel the joy of friendship in banking. </p>
          </blockquote>
        </div>
          <div class="col-md-6">
              <div align="center" class="form2" >
                <form action="{% url 'bank:register' %}" method="post">
                    {% csrf_token %}
                    <div class="display-2 " align="center">
                        <h2 class="h"><b>REGISTRATION</b></h2>
                    </div>
                    <div class="form-group" >
                        <i class="fa fa-user" style="font-size:25px"></i> <input class=" input1" type="text"  name="uname" aria-describedby="emailHelp" placeholder="enter your username">
                    </div>
                    <div class="form-group">
                        <i class="fa fa-lock" style="font-size:25px"></i> <input class="input" type="password"  name="pass" placeholder="enter your password">
                    </div>
                    <div class="form-group">
                        <i class="fa fa-lock" style="font-size:25px"></i> <input class="input" type="password" name="cpass"  placeholder="confirm your password">
                    </div>
                    <br><br>
                    <input type="submit" class="btn-get-started" >

<!--                    <a href="" class="">Register</a>-->
                </form>
            </div>
          </div>

      </div>
    </div>
</section>

{% endblock %}

bankproject/templates/success.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Raleway:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/main.css' %}" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/a076d05399.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/solid.min.css" integrity="sha512-uj2QCZdpo8PSbRGL/g5mXek6HM/APd7k/B5Hx/rkVFPNOxAQMXD+t+bG4Zv8OAdUpydZTU3UHmyjjiHv2Ww0PA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<!--  new modal-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>


</head>
<body>
<section id="hero" class="hero d-flex align-items-center">
    <div class="container">
      <div class="row">
        <div class="col-xl-4">
            {% if user.is_authenticated %}
            <h2 data-aos="fade-up">Hello {{ user.username }}</h2>
            {% endif %}
          <blockquote data-aos="fade-up" data-aos-delay="100">
            <div>

            </div>
          </blockquote>
        </div>
          <div class="col-xl-8">
              <table>
                  {% for m in messages %}
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        <strong>{{ m }}</strong>
                    </div>
                  {% endfor %}
                  <div align="center">
                      <a href="{% url 'bank:home' %}" class="btn-get-started">home</a>
                      <a href="{% url 'bank:logout' %}" class="btn-get-started">logout</a>
                  </div>
              </table>

          </div>
      </div>
    </div>
</section>


  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>
  <script src="{% static 'assets/js/semantic.js' %}" defer></script>
  <script src="{% static 'assets/js/modal.js' %}" defer></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>